micronaut:
  application:
    name: backend
  server:
    port: 8080
    thread-selection: auto # https://github.com/micronaut-projects/micronaut-core/issues/3651
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  jcache:
    enabled: false
jackson:
  bean-introspection-module: true

noop-cache.enabled: ${ENABLE_CACHE:true}

redis:
  uri: redis://${REDI_URI:localhost}
  caches:
    all:
      expire-after-write: 15m
    find-by-borough:
      expire-after-write: 15m
    find-by-name:
      expire-after-access: 15m
    find-by-borough-and-Name:
      expire-after-access: 15m
  timeout: 5s

services:
  minsal:
    url: ${MINSAL_URL:`https://farmanet.minsal.cl`}
    path: ${MISNAL_PATH:`/maps/index.php/ws/getLocalesRegion`}
    param: ${MINSAL_PARAM:`id_region`}
    value: ${MINSAL_VALUE:7}